apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    dc3.service: dc3-rabbitmq
  name: dc3-rabbitmq
  namespace: kube-dc3
spec:
  replicas: 1
  selector:
    matchLabels:
      dc3.version: develop
      dc3.network/dc3net: "true"
      dc3.service: dc3-rabbitmq
  template:
    metadata:
      labels:
        dc3.version: develop
        dc3.network/dc3net: "true"
        dc3.service: dc3-rabbitmq
    spec:
      containers:
        - image: pnoker/dc3-rabbitmq:3.0
          name: dc3-rabbitmq
          ports:
            - containerPort: 5672
            - containerPort: 1883
            - containerPort: 61613
            - containerPort: 15672
      hostname: dc3-rabbitmq
      restartPolicy: Always