driver:
  name: OpcUaDriver
  description: @project.description@
  schedule:
    read:
      enable: true
      corn: '0/30 * * * * ?'
    custom:
      enable: false
      corn:  '0/30 * * * * ?'
  driver-attribute:
    - displayName: 主机
      name: host
      type: string
      value: localhost
      description: Ip
    - displayName: 端口
      name: port
      type: int
      value: 18600
      description: Port
  point-attribute:
    - displayName: 位号
      name: tag
      type: string
      value: TAG
      description: 位号名称

server:
  port: 8603

spring:
  application:
    name: @project.artifactId@

logging:
  level:
    com.github.pnoker.common.sdk: DEBUG
    com.github.pnoker: DEBUG
  file:
    name: dc3/logs/driver/opcua/${spring.application.name}.log