driver:
  name: OpcDaDriver
  description: @project.description@
  schedule:
    read:
      enable: true
      corn: '0/30 * * * * ?'
    custom:
      enable: false
      corn:  '0/30 * * * * ?'
  driver-attribute:
    - displayName: 主机
      name: host
      type: string
      value: localhost
      description: Opc Da Host
    - displayName: 域
      name: domain
      type: string
      value: ''
      description: Opc Da Domain
    - displayName: 用户名
      name: username
      type: string
      value: ''
      description: Opc Da UserName
    - displayName: 密码
      name: password
      type: string
      value: ''
      description: Opc Da Passward
  point-attribute:
    - displayName: 分组
      name: group
      type: string
      value: GROUP
      description: 分组名称
    - displayName: 位号
      name: tag
      type: string
      value: TAG
      description: 位号名称

server:
  port: 8601

spring:
  application:
    name: @project.artifactId@

logging:
  level:
    com.freud.dcom.utgard.cases.*: INFO
    com.github.pnoker.common.sdk: DEBUG
    com.github.pnoker: DEBUG
  file:
    name: dc3/logs/driver/opcda/${spring.application.name}.log