server:
  port: 8200
  undertow:
    threads:
      io: 2
      worker: 20
    buffer-size: 512

spring:
  application:
    name: @project.artifactId@
  security:
    user:
      name: ${SECURITY_USER_NAME:dc3}
      password: ${SECURITY_USER_PASSWORD:dc3}
  transaction:
    rollback-on-commit-failure: true
  boot:
    admin:
      context-path: ${MONITOR_CONTEXT_PATH:/}
      ui:
        title: DC3 Monitor Center
        public-url: ${MONITOR_PUBLIC_URL:/}
        favicon: /monitor/images/icon/favicon.ico
        favicon-danger: /monitor/images/icon/favicon-danger.ico
        brand: <img src="/monitor/images/logo/dc3-logo.png"><span>DC3 Monitor Center</span>

logging:
  level:
    com.dc3: DEBUG
    de.codecentric.boot.admin: ERROR
  file:
    name: dc3/logs/center/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-history: 30
      total-size-cap: 2GB
      clean-history-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  instance:
    prefer-ip-address: true
    hostname: @project.artifactId@
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 15
  client:
    region: dc3
    availability-zones:
      dc3: defaultZone
    prefer-same-zone-eureka: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${EUREKA_HOST:dc3-register}:${EUREKA_PORT:8100}/eureka/