apiVersion: v1
kind: Service
metadata:
  labels:
    dc3.service: dc3-data
  name: dc3-data
  namespace: kube-dc3
spec:
  ports:
    - name: "8500"
      port: 8500
      targetPort: 8500
  selector:
    dc3.version: develop
    dc3.network/dc3net: "true"
    dc3.service: dc3-data