apiVersion: v1
kind: Service
metadata:
  labels:
    dc3.service: dc3-auth
  name: dc3-auth
  namespace: kube-dc3
spec:
  ports:
    - name: "8400"
      port: 8400
      targetPort: 8400
  selector:
    dc3.version: develop
    dc3.network/dc3net: "true"
    dc3.service: dc3-auth