apiVersion: v1
kind: Service
metadata:
  labels:
    dc3.service: dc3-nginx
  name: dc3-nginx
  namespace: kube-dc3
spec:
  ports:
    - name: "1935"
      port: 1935
      targetPort: 1935
  selector:
    dc3.version: develop
    dc3.network/dc3net: "true"
    dc3.service: dc3-nginx