apiVersion: v1
kind: Service
metadata:
  labels:
    dc3.service: dc3-redis
  name: dc3-redis
  namespace: kube-dc3
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    dc3.version: develop
    dc3.network/dc3net: "true"
    dc3.service: dc3-redis